include:
  - apps/koa-app/compose.yaml
  - apps/next14-app/compose.yaml
  - apps/nginx-proxy/compose.yaml
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
