name: nginx-proxy
services:
  proxy1:
    image: nginx:1.27-alpine-slim
    container_name: proxy1
    networks:
      frontend:
        ipv4_address: 192.168.1.10
    ports:
      - "9000:80"
    volumes:
      - ./proxy1/default.conf:/etc/nginx/conf.d/default.conf:ro
    develop:
      watch:
        - action: restart
          path: ./proxy1/default.conf
  proxy2:
    image: nginx:1.27-alpine-slim
    container_name: proxy2
    networks:
      frontend:
        ipv4_address: 192.168.1.11
    ports:
      - "9001:80"
    volumes:
      - ./proxy2/default.conf:/etc/nginx/conf.d/default.conf:ro
    develop:
      watch:
        - action: restart
          path: ./proxy2/default.conf
  proxy3:
    image: nginx:1.27-alpine-slim
    container_name: proxy3
    networks:
      frontend:
        ipv4_address: 192.168.1.12
    ports:
      - "9002:80"
    volumes:
      - ./proxy3/default.conf:/etc/nginx/conf.d/default.conf:ro
    develop:
      watch:
        - action: restart
          path: ./proxy3/default.conf
