name: nginx-proxy
services:
  proxy1:
    image: nginx:1.27-alpine-slim
    container_name: proxy1
    ports:
      - "9000:80"
    volumes:
      - ./proxy1/default.conf:/etc/nginx/conf.d/default.conf:ro
    develop:
      watch:
        - action: restart
          path: ./proxy1/default.conf
  proxy2:
    image: nginx:1.27-alpine-slim
    container_name: proxy2
    ports:
      - "9001:80"
    volumes:
      - ./proxy2/default.conf:/etc/nginx/conf.d/default.conf:ro
    develop:
      watch:
        - action: restart
          path: ./proxy2/default.conf
