name: koa-app
services:
  koa-app:
    build:
      context: ../..
      target: koa-app
    container_name: koa-app
    networks:
      frontend:
        ipv4_address: 192.168.1.14
    ports:
      - "8001:8001"
    develop:
      watch:
        - path: .
          action: rebuild
