name: koa-app
services:
  koa-app:
    container_name: koa-app
    build:
      context: ../..
      target: koa-app
    ports:
      - "8001:8001"
    develop:
      watch:
        - path: .
          action: rebuild
